library(tidyverse)
library(janitor)
library(tidymodels)
library(tidytext)
library(embed)

Vicia_Cell_wall_mass.share_MEAN
Vicia_Copper_DESORBTION_root_MEAN
Vicia_Copper_DESORBTION_shoot_MEAN
Vicia_mass_MEAN
Vicia_Copper_ENDOGEN_CONT_root_MEAN
Vicia_Copper_ENDOGEN_CONT_shoot_MEAN
Vicia_pH.root_MEAN
Vicia_pH.shoot_MEAN
Vicia_pH.Intact_Plants_MEAN



